AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  Max: 9999

Metrics/LineLength:
  Max: 120

Style/SignalException:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
