AllCops:
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: '2.1'

Metrics/BlockLength:
  Max: 9999

Metrics/LineLength:
  Max: 120

Style/IndentArray:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
