language: ruby
cache: bundler

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

script:
  - .travis/danger.sh

  - echo 'Linting...'
  - bundle exec rake lint

  - echo 'Test...'
  - bundle exec rake tests

branches:
  only:
    - master
    - develop
